apiVersion: v1
kind: Service
metadata:
  name: api

spec:
  ports:
    - protocol: TCP
      name: web
      port: 8080
  selector:
    app: api
---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: default
  name: api
  labels:
    app: api

spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: "musty01/4pjt-api"
          ports:
            - name: web
              containerPort: 8080